[build-system]
requires = ["flit_core >=3.2,<4","myst-parser"]
build-backend = "flit_core.buildapi"

[project]
name = "MyTutorial"
authors = [{name = "Kaikai Liu", email = "kaikai.liu@sjsu.edu"}]
dynamic = ["version", "description"]
